CREATE SCHEMA ADDRESS_SCHEMA
GO

ALTER SCHEMA ADDRESS_SCHEMA TRANSFER dbo.ADDRESS;
ALTER SCHEMA ADDRESS_SCHEMA TRANSFER dbo.EMPLOYEEADDRESS;

SELECT * FROM ADDRESS_SCHEMA.ADDRESS;
SELECT * FROM ADDRESS_SCHEMA.EMPLOYEEADDRESS;