CREATE SCHEMA FACILITY_SCHEMA
GO
ALTER SCHEMA FACILITY_SCHEMA TRANSFER dbo.REGIONS;
ALTER SCHEMA FACILITY_SCHEMA TRANSFER dbo.COUNTRIES;
ALTER SCHEMA FACILITY_SCHEMA TRANSFER dbo.FACILITYADDRESS;
SELECT * FROM FACILITY_SCHEMA.REGIONS;
SELECT * FROM FACILITY_SCHEMA.COUNTRIES;
SELECT * FROM FACILITY_SCHEMA.FACILITYADDRESS;