USE [Orders Database]

SELECT * FROM CATEGORY; --1


SELECT CUSTOMERORDER.ORDERID, CUSTOMERORDER.TOTALPAID, SHIPMENTMETHOD.SHIPMENTMODE FROM CUSTOMERORDER  JOIN SHIPMENTMETHOD
ON SHIPMENTMETHOD.SHIPMENTMETHODID = CUSTOMERORDER.SHIPMENTMETHODID;--3


SELECT * FROM CUSTOMERORDER WHERE TOTALPAID < '1000'---4


SELECT * FROM CUSTOMERORDER WHERE ESTDATESHIPPED = ACTUALDATESHIPPED; ---5


SELECT 
     CUSTOMERORDER. OrderID, ORDERSTATUS.OrderStatus_Description
FROM
    CUSTOMERORDER
        INNER JOIN
    ORDERSTATUS ON (CUSTOMERORDER.OrderStatusID = ORDERSTATUS.OrderStatusID)
WHERE
    OrderStatus_Description IN ('In Transit', 'Delayed'); ---6



SELECT 
    Product.ProductID, Product.Product_Description,REVIEW.Rating
FROM Product INNER JOIN
    REVIEW ON (Product.ProductID = REVIEW.ProductID)
WHERE REVIEW.Rating >=4;---7



SELECT SHIPMENTMETHOD.ShipmentMode, COUNT(CUSTOMERORDER.ORDERID)
FROM CUSTOMERORDER,SHIPMENTMETHOD
WHERE
    CUSTOMERORDER.ShipmentMethodID = SHIPMENTMETHOD.ShipmentMethodID
GROUP BY SHIPMENTMETHOD.ShipmentMode;---8



SELECT * FROM PRODUCT where ProductID NOT IN (SELECT ProductID FROM PRODUCTSELECTION);---9


Select OrderID,CustomerID,ActualDateShipped from CUSTOMERORDER where MONTH(ActualDateShipped)=9---10


select OrderID, CustomerID from CustomerOrder where Year(EstDateShipped)='2021';--11


select OrderID, CustomerID from CustomerOrder where month(ActualDateShipped)='10' and Year(ActualDateShipped) <> '2020';--12


Select * from Product order by Price DESC;---13


Select  TOP 3 OrderID, SUM(UnitPriceSold) as TotalPrice
from ProductSelection
GROUP BY OrderID
ORDER BY SUM(UnitPriceSold) DESC;---14


Select Count(ProductID) as TotalProductOrdered from ProductSelection; ---15


SELECT CUSTOMERID AS CUSTOMER,COUNT(CUSTOMERID) AS CUSTOMER_COUNT FROM CUSTOMERORDER
GROUP BY CUSTOMERID;---16


SELECT * FROM PRODUCT WHERE PRODUCTID IN(
SELECT PRODUCTID FROM REVIEW WHERE RATING BETWEEN 3 AND 5 AND PRODUCTID IN (
SELECT PRODUCTID FROM PRODUCT WHERE PRODUCTCATEGORYID IN ( SELECT PRODUCTCATEGORYID FROM CATEGORY
WHERE CATEGORYNAME IN ('Perishable','Miscellaneous')))) ---17


SELECT * FROM CUSTOMERORDER WHERE ORDERID IN(
SELECT ORDERID FROM PRODUCTSELECTION WHERE PRODUCTID IN (SELECT PRODUCTID FROM PRODUCT WHERE PACKAGE LIKE 'Gi%') ) --18



SELECT CUSTOMERORDER.CUSTOMERID,CUSTOMERORDER.ORDERID,PRODUCTSELECTION.PRODUCTID,PRODUCT.PRODUCT_DESCRIPTION,PRODUCT.PRICE,PRODUCT.WeightUnits
FROM CUSTOMERORDER
JOIN PRODUCTSELECTION  ON PRODUCTSELECTION.ORDERID = CUSTOMERORDER.ORDERID 
JOIN PRODUCT PRODUCT ON PRODUCT.PRODUCTID = PRODUCTSELECTION.PRODUCTID
WHERE PRODUCT.WeightUnits > 1000
ORDER BY CUSTOMERID ; ---19

 
SELECT CUSTOMERORDER.CUSTOMERID,CUSTOMERORDER.ORDERID,PRODUCTSELECTION.PRODUCTID,PRODUCT.PRODUCT_DESCRIPTION,PRODUCT.PRICE AS PRICE
FROM CUSTOMERORDER 
JOIN PRODUCTSELECTION ON PRODUCTSELECTION.ORDERID = CUSTOMERORDER.ORDERID 
JOIN PRODUCT  ON PRODUCT.PRODUCTID = PRODUCTSELECTION.PRODUCTID
ORDER BY CUSTOMERID ;  ---20
-------------------------------












